### PR TITLE
Add Goodreads series.show method support to list books of a series

### PR DESCRIPTION
**Pull request by enribd**

### CODE REVIEW

**Review by KyleBanks — APPROVED** [review]
Thanks! 💯

**Comment by KyleBanks** [comment]
Would you mind adding tests and running go fmt?

**Review by KyleBanks — CHANGES_REQUESTED** [review]
Would you mind adding tests and running go fmt?

**Comment by enribd** [comment]
I will do it as soon as I've time! ;)

**Comment by enribd** [comment]
Closed this PR since I messed up commit history

**Pull request closed without merging**
